version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: fyhwek+1t(aE
      MYSQL_PASSWORD: fyhwek+1t(aE
      MYSQL_DATABASE: book_store
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - /mysql:/var/lib/mysql